/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCalendar1: typeof import('./components/Calendar/BaseCalendar1.vue')['default']
    BaseCalendar2: typeof import('./components/Calendar/BaseCalendar2.vue')['default']
    BaseCalendar3: typeof import('./components/Calendar/BaseCalendar3.vue')['default']
    BaseCalendar4: typeof import('./components/Calendar/BaseCalendar4.vue')['default']
    BaseCalendar5: typeof import('./components/Calendar/BaseCalendar5.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
