#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install lint-staged

echo "---ts检查开始---"
npm run type-check
echo "---ts检查结束---"

# Previous HUSKY_GIT_PARAMS environment variable is replaced by native params $1, $2, etc.
# node scripts/verify-commit-msg.cjs --name=$1

