#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install lint-staged

# Previous HUSKY_GIT_PARAMS environment variable is replaced by native params $1, $2, etc.
# node scripts/verify-commit-msg.cjs --name=$1

